// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5o155iNfmragdVz5piADdQxLE1Uo34_I',
    appId: '1:1010964226172:web:a1db4b54d66b645b0ee9f9',
    messagingSenderId: '1010964226172',
    projectId: 'queue-management-8d345',
    authDomain: 'queue-management-8d345.firebaseapp.com',
    storageBucket: 'queue-management-8d345.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9L1PzpT5WeWb9oA8SFaSgxdtUsD928og',
    appId: '1:1010964226172:android:d74926e1659348cb0ee9f9',
    messagingSenderId: '1010964226172',
    projectId: 'queue-management-8d345',
    storageBucket: 'queue-management-8d345.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAhmvazkb-D-YcnZgVeyNjtLeJjRet6IA',
    appId: '1:1010964226172:ios:5c1e5a138467c2430ee9f9',
    messagingSenderId: '1010964226172',
    projectId: 'queue-management-8d345',
    storageBucket: 'queue-management-8d345.appspot.com',
    iosClientId: '1010964226172-fj4f2oefa57vqo4f9pdmu7ouo93e3nhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.queueFullstack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAhmvazkb-D-YcnZgVeyNjtLeJjRet6IA',
    appId: '1:1010964226172:ios:5c1e5a138467c2430ee9f9',
    messagingSenderId: '1010964226172',
    projectId: 'queue-management-8d345',
    storageBucket: 'queue-management-8d345.appspot.com',
    iosClientId: '1010964226172-fj4f2oefa57vqo4f9pdmu7ouo93e3nhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.queueFullstack',
  );
}
